services:
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: "aozora-mssql"
    ports:
      - 1433:1433
    volumes:
      - ./.dev/mssql:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: p@ssw0rd#mssql
